server:
  port: 8080

spring:
  datasource:
    name:
    url: jdbc:mysql://127.0.0.1:3306/exampleboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 111111

mybatis:
  mapper-locations: classpath:mapper/*.xml
